Game logic Milestone 3
sneeu-leeu/Tic-Tac-Toe-OOP pull request #4
Opened 2020-10-22 13:34 UTC by tahiry-dev

## This is milestone 3- executable game
#### In this Milestone we:
- Implemented the Object-Oriented Programming with the previous logic
- Separate the logic from the interface with classes
- Improve the user experiences by adding a more meaningful message

2020-10-22 15:05 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for the well-done job so far
The Game is working like a charm

However, there are some issues 

1- Kindly use the rubocop.yml file required. Follow this [link](https://github.com/microverseinc/linters-config/tree/master/ruby), please, to get the good rubocop.yml file

2- There are many rules added to pass rubocop tests. It is not really good all at all.  Remove them and fix the corresponding errors

3- Sorry, but your OOP implementation is not good. It's more like a procedural implementation. Kindly, please, read the comments left below.  It will help you to learn more about OOP.

Once solve all the issues, submit a new code review request

Thanks

Mael FOSSO

2020-10-22 15:05 UTC, maelfosso commented on lib/board.rb
> +    puts
No `puts/gets/print` in any code from the `lib` folder

2020-10-22 15:05 UTC, maelfosso commented on lib/player.rb
> +end
That class is not needed.
We should remove it, please.

Moreover, there are a lot of rubocop rules. Which indicates wrong things.

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
> +
**OPTIONAL**

There is too much `sleep` in your code.
In the end, it bothers when trying to play.

2020-10-22 15:05 UTC, maelfosso commented on lib/board.rb
> +  attr_accessor :tokens
`attr_accessor` is not really allowed.
Use `attr_reader` or `attr_writter`, please. And you case, it's more `attr_reader`

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
>        puts 'The selected cell is invalid!'
Instead of `loop 1` and `loop 2`, implement a method called `switch_current_player`.
Call it at the end of each turn to know what player is the turn

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
> +    operation = ArrayOperation.new(board, choice_2.choice)
Those 2 lines show that there is a problem in the way you design the application.
You OOP (which is the main goal of this project) is not good

You pass `board` in two classes, just for using one method in each of them
- `inside?` from **Position**
- `to_deleteArr` from **ArrayOperation**

A better way to implement that using OOP, is to

1. Create a class called `Board`

2. Add into that class an attribute `attr_reader :board`

3. Initialize `:board` attribute with `[1, 2, 3, 4, 5, 6, 7, 8, 9]`

4. Add into that `Board` class, two methods: `invalid?` and `to_deleteArr`

5. Update your code like this

```rb
choice = gets.chomp.to_i
if board.inside?(choice)
  board.to_deleteArr(choice, player.name || player.token)
end 
```

You will notice that in that better case, `to_deleteArr` will not remove a value from the array, just update a position into the array with the token of the current player

2020-10-22 15:05 UTC, maelfosso commented on lib/logic.rb
> +  @@arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 4, 7], [2, 5, 8], [3, 6, 9], [1, 5, 9], [3, 5, 7]] # rubocop:todo Style/ClassVars
That is a constant.
Define it as a Ruby Constant, please.

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
> +  first_player = Logic.new(board_1)
Also the simple fact to pass `board` as a parameter in three classes (Position, ArrayOperation and Logic) is a prove of an error into your OOP implementation

As indicated above, merge the three class into one class called `Board` and all their method must now be the methods of that new `Board` class.

Dont forget to add an attribute `attr_reader :board`.

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
>  board_2 = [] # rubocop:todo Naming/VariableNumber
Not needed. Kindly remove them, please.

2020-10-22 15:05 UTC, maelfosso commented on bin/main.rb
>  until breakpoint.zero?
Instead, a better approach can be this one
```rb
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

2020-10-23 18:55 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job implementing the changes. However, I am not able to play the game. When I run `bin/main.rb` or `ruby bin/main.rb`, I get the following error:**

![console](https://user-images.githubusercontent.com/38922385/97040777-1f93bf00-1577-11eb-8bac-7696c72c6936.png)

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-10-23 20:54 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for implementing the suggested changes.
Your code is better now.
However, there are still some issues.

Kindly read the comment left below and once solved, submit a new code review request
Thanks

Mael FOSSO

2020-10-23 20:54 UTC, maelfosso commented on lib/winner.rb
> +  # rubocop:todo Naming/VariableName
Remove that and fix the issues, please

2020-10-23 20:54 UTC, maelfosso commented on lib/winner.rb
> +  @@WINNING_POS = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 4, 7], [2, 5, 8], [3, 6, 9], [1, 5, 9], [3, 5, 7]]
Declare it as a **CONSTANT**

Read this [article](http://rubylearning.com/satishtalim/ruby_constants.html) to know create RUBY CONSTANT

2020-10-23 20:54 UTC, maelfosso commented on bin/main.rb
> +  is_winner = Winner.new(current_player.choice)
This line indicates a wrong OOP design.
The current player choices you pass in parameters are used without any modification in the Winner class and moreover, the Winner class contains only one method checking the winner.

A better OOP implemention, according to your approach, is to merge the `Player` and `Winner` classes. 
You will no longer have to pass the current player's choices to any method. You will just do
```rb
current_player.real_win?
```

2020-10-23 20:54 UTC, maelfosso commented on lib/player.rb
> +end
Same comments, please. Fix them.

2020-10-23 22:35 UTC, tahiry-dev commented
-The first review we got is about an error when running the game, however, the game runs properly. Please Have a look at the attached screenshot
![main rb](https://user-images.githubusercontent.com/47100064/97059195-7362d000-1598-11eb-846c-7ffb450e16eb.png)
![ruby-bin-main](https://user-images.githubusercontent.com/47100064/97059204-7958b100-1598-11eb-84b5-dffaa1124efc.png)

-We are suggested to merge Player and Winner classes but we didn't, because we tried to follow the Single Responsibility Principle regardless of the number of  methods a class may contain

2020-10-24 03:13 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Steph Annandale & Tahiry Randriamiarintsoa** 
Nice job with the improvements for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Don't overuse the rubocop disabling option
- [ ] In your main file, divide the logic into different functions
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-10-24 15:02 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Steph Annandale & Tahiry Randriamiarintsoa** 
Nice job with the improvements for this project :muscle:  :muscle:
Still, the problems from the previous review remain:

- [ ] You are still overusing the rubocop disabling option
- [ ] In your main file, divide the logic into different functions
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-10-24 15:32 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello Team  👋 
You are doing a great job with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received from the other TSEs. 🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The game does not allow a player to move into an occupied spot 👏 👏 However, it does not ask the player to choose a new position. Instead it switches to the other player.
Screenshot of gameplay 👇 
![Screen Shot 2020-10-24 at 5 28 48 PM](https://user-images.githubusercontent.com/48804258/97085533-625ca200-161e-11eb-931a-ffdddf3b3a8b.png)

- [ ] The game ends with a draw even if there are available spaces on the board 👇 
![Screen Shot 2020-10-24 at 5 30 06 PM](https://user-images.githubusercontent.com/48804258/97085572-90da7d00-161e-11eb-8715-1cf7f85f5fff.png)
    

****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-10-25 11:36 UTC, krys2fa commented
# Status: Milestone Approved! 🥇 
Congratulations on making all the previous reviewer's requested changes and getting this milestone approved. 👍 


Below is an **optional** request to make your game even better.
- [ ] [OPTIONAL] It will be nice to have your game ask if the players want to play again or end the game completely. In this case, the game should respond appropriately either by starting all over or ending.

You can now merge this branch into the development branch and go on with your next milestone.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-10-25 18:06 UTC, merged